// <auto-generated />
namespace MyUserManagementApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class InitializeUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitializeUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202412310516589_InitializeUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
